import turtle
turtle.hideturtle()
turtle.speed(0)
turtle.pensize(2)

turtle.circle(30)
turtle.penup()
turtle.goto(0, 60)
turtle.pendown()
turtle.circle(25)
turtle.penup()
turtle.goto(0, 110)
turtle.pendown()
turtle.circle(20)

turtle.penup()
turtle.goto(-7, 135)
turtle.dot(3)
turtle.goto(7, 135)
turtle.dot(3)

turtle.goto(0, 124)
turtle.color("orange")
turtle.pendown()
turtle.goto(15, 127)
turtle.goto(0, 130)
turtle.goto(0, 124)
